(ns kami.bim-editor.ui (:require [html.core :as html] [css.core :as css]))
(def sheet {:rules {"*" {:box-sizing :border-box} "body" {:margin 0 :height "100vh" :display :grid :grid-template-rows "52px 1fr" :font-family "Inter,system-ui" :background "#09101c" :color "#e7ecfa"} "header" {:padding "0 16px" :display :flex :align-items :center :gap 8 :overflow-x :auto :background "#121c38"} "header .spacer" {:flex 1} "header button,header select" {:width :auto :white-space :nowrap} "main" {:display :grid :grid-template-columns "260px 1fr 300px" :min-height 0} "aside" {:padding 16 :overflow-y :auto :background "#111a34" :border-right "1px solid #2d3e68"} "aside:last-child" {:border-left "1px solid #2d3e68" :border-right 0} ".viewport" {:position :relative} "#gpu-canvas" {:width "100%" :height "100%" :display :block} "#gpu-status" {:position :absolute :left "50%" :top "45%" :transform "translate(-50%,-50%)" :color "#ffb0b0"} ".viewport-help" {:position :absolute :left 14 :bottom 14 :padding 8 :background "#08101dcc" :color "#b9c8e8" :font-size 11 :pointer-events :none} ".drag-measure" {:position :absolute :left "50%" :top 18 :transform "translateX(-50%)" :padding "7px 10px" :background "#09101cee" :border "1px solid #f59e0b" :color "#ffd28a" :font-size 12 :pointer-events :none} ".snap-marker" {:position :absolute :width 12 :height 12 :transform "translate(-50%,-50%) rotate(45deg)" :border "2px solid #fbbf24" :background "#111827aa" :pointer-events :none} ".selection-box" {:position :absolute :border "1px solid #60a5fa" :background "#3b82f633" :pointer-events :none} "button,input,select" {:width "100%" :margin "5px 0" :padding 8 :background "#20315b" :border "1px solid #526fa9" :border-radius 5 :color "#e7ecfa"} "button" {:cursor :pointer :text-align :left} ".primary" {:background "#7da2f3" :color "#071226" :font-weight 700} "h2" {:font-size 11 :margin-top 20 :text-transform :uppercase :letter-spacing ".1em" :color "#a7b9e0"} "label" {:display :grid :gap 4 :margin "9px 0"} ".stats" {:position :absolute :right 14 :bottom 14 :padding 8 :background "#08101dcc"} ".selected" {:border-color "#9fb9ff" :background "#314a82"}}})
(defn page []
  (html/html5
   [:html {:lang "en"}
    [:head [:meta {:charset "utf-8"}]
     [:meta {:name "viewport" :content "width=device-width,initial-scale=1"}]
     [:link {:rel "icon" :href "data:,"}] [:title "Kami BIM Editor"]
     [:style (css/css sheet)]]
    [:body
     [:header [:strong "KAMI BIM EDITOR"] [:span "Semantic building workspace"] [:span.spacer]
      [:select {:id "profile" :aria-label "Interaction profile"}
       [:option {:value "revit"} "Revit"] [:option {:value "archicad"} "Archicad"]
       [:option {:value "vectorworks"} "Vectorworks"]]
      [:button {:id "undo"} "Undo"] [:button {:id "redo"} "Redo"]
      [:button {:id "save-project"} "Save"] [:button {:id "load-project"} "Load"]
      [:button {:id "import"} "Import"]
      [:input {:id "import-file" :type "file" :accept ".edn,.kami-bim.edn" :style {:display "none"}}]
      [:button {:id "export"} "Export Project"] [:button {:id "export-ifc"} "Export IFC"]
      [:button {:id "import-ifc"} "Import IFC"]
      [:input {:id "import-ifc-file" :type "file" :accept ".ifc" :style {:display "none"}}]
      [:button {:id "publish-opencde"} "Publish OpenCDE"]
      [:button {:id "export-bcf"} "Export BCF"]
      [:button {:id "refresh-stream"} "Refresh LOD"]
      [:span {:id "workspace-status"} "Workspace ready"]
      [:select {:id "drawing-kind" :aria-label "Drawing kind"}
       [:option {:value "plan"} "Plan"] [:option {:value "section"} "Section"]
       [:option {:value "elevation"} "Elevation"] [:option {:value "sheet"} "Sheet"]]
      [:select {:id "drawing-format" :aria-label "Drawing format"}
       [:option {:value "svg"} "SVG"] [:option {:value "pdf"} "PDF"]
       [:option {:value "dxf"} "DXF"]]
      [:button {:id "export-drawing"} "Export Drawing"]]
     [:main
      [:aside
       [:h2 "Elements"] [:p {:id "profile-hint"} "WA Wall · DR Door · WN Window · LL Level · FL Floor"]
       [:button.primary {:id "add-wall"} "＋ Wall"] [:button {:id "add-slab"} "＋ Floor slab"]
       [:label "Roof width (m)" [:input {:id "roof-width" :type "number" :min 0.1 :step 0.5 :value 8}]]
       [:label "Roof depth (m)" [:input {:id "roof-depth" :type "number" :min 0.1 :step 0.5 :value 6}]]
       [:label "Roof slope (deg)" [:input {:id "roof-slope" :type "number" :min 1 :max 89 :step 1 :value 30}]]
       [:label "Roof thickness (m)" [:input {:id "roof-thickness" :type "number" :min 0.01 :step 0.05 :value 0.2}]]
       [:button {:id "add-roof"} "＋ Gable roof (RF)"]
       [:label "Stair width (m)" [:input {:id "stair-width" :type "number" :min 0.1 :step 0.1 :value 1.2}]]
       [:label "Stair run (m)" [:input {:id "stair-run" :type "number" :min 0.1 :step 0.1 :value 3.6}]]
       [:label "Stair rise (m)" [:input {:id "stair-rise" :type "number" :min 0.1 :step 0.1 :value 3.2}]]
       [:label "Risers" [:input {:id "stair-risers" :type "number" :min 2 :step 1 :value 18}]]
       [:button {:id "add-stair"} "＋ Straight stair (ST)"]
       [:label "Railing path (x,y,z; …)" [:input {:id "railing-path" :value "0,0,0;4,0,0;4,3,0"}]]
       [:label "Railing height (m)" [:input {:id "railing-height" :type "number" :min 0.1 :step 0.1 :value 1.1}]]
       [:label "Post spacing (m)" [:input {:id "railing-spacing" :type "number" :min 0.1 :step 0.1 :value 1.0}]]
       [:button {:id "add-railing"} "＋ Path railing (RL)"]
       [:label "Curtain width (m)" [:input {:id "curtain-width" :type "number" :min 0.1 :step 0.5 :value 8}]]
       [:label "Curtain height (m)" [:input {:id "curtain-height" :type "number" :min 0.1 :step 0.5 :value 4}]]
       [:label "Curtain columns" [:input {:id "curtain-columns" :type "number" :min 1 :step 1 :value 4}]]
       [:label "Curtain rows" [:input {:id "curtain-rows" :type "number" :min 1 :step 1 :value 2}]]
       [:button {:id "add-curtain"} "＋ Curtain wall (CW)"]
       [:button {:id "add-door"} "＋ Door in selected wall"] [:button {:id "add-window"} "＋ Window in selected wall"]
       [:h2 "Families"] [:label "Definition" [:select {:id "family-definition"} [:option {:value "casework"} "Casework"]]]
       [:label "Type" [:select {:id "family-type"}]]
       [:label "Family ID" [:input {:id "family-id" :value "casework"}]]
       [:label "Family name" [:input {:id "family-name" :value "Casework"}]]
       [:label "Category" [:select {:id "family-category"}
                            (for [value ["furniture" "door" "window" "equipment" "generic-model"]]
                              [:option {:value value} value])]]
       [:label "Type width (m)" [:input {:id "family-width" :type "number" :min 0.01 :step 0.1 :value 0.8}]]
       [:label "Depth (m)" [:input {:id "family-depth" :type "number" :value 0.6}]]
       [:label "Height (m)" [:input {:id "family-height" :type "number" :value 0.9}]]
       [:label "Material" [:input {:id "family-material" :value "Oak"}]]
       [:label "Shared family" [:input {:id "family-shared" :type "checkbox"}]]
       [:label "Parameters (EDN)"
        [:textarea {:id "family-parameters" :rows 6} "{}"]]
       [:label "Lookup tables (EDN)"
        [:textarea {:id "family-lookup-tables" :rows 5} "{}"]]
       [:label "Formulas (EDN)"
        [:textarea {:id "family-formulas" :rows 3} "{}"]]
       [:label "Reference planes (EDN)"
        [:textarea {:id "family-reference-planes" :rows 3} "{}"]]
       [:label "Constraints (EDN)"
        [:textarea {:id "family-constraints" :rows 3} "[]"]]
       [:label "Sketches (EDN)"
        [:textarea {:id "family-sketches" :rows 5} "{}"]]
       [:label "Family template (EDN)"
        [:textarea {:id "family-template" :rows 8} "{}"]]
       [:button {:id "save-family-definition"} "Save family definition"]
       [:label "Type name" [:input {:id "family-type-name" :value "Standard"}]]
       [:button {:id "save-family-type"} "Save family type"]
       [:label "Display detail" [:select {:id "family-detail"}
                                  [:option {:value "coarse"} "Coarse"]
                                  [:option {:value "medium" :selected true} "Medium"]
                                  [:option {:value "fine"} "Fine"]]]
       [:button.primary {:id "add-family-instance"} "＋ Family instance"]
       [:div {:id "family-status"} "Family ready"]
       [:h2 "Engineering"]
       [:label "Structural role" [:select {:id "structural-role"}
                                  [:option {:value "beam"} "Beam"]
                                  [:option {:value "column"} "Column"]
                                  [:option {:value "shear-wall"} "Shear wall"]
                                  [:option {:value "diaphragm"} "Diaphragm"]]]
       [:label "Section width (m)" [:input {:id "structural-width" :type "number" :min 0.01 :value 0.25}]]
       [:label "Section depth (m)" [:input {:id "structural-depth" :type "number" :min 0.01 :value 0.5}]]
       [:button {:id "assign-structural-role"} "Assign selected structural role"]
       [:button {:id "generate-structural-model"} "Generate analytical model"]
       [:label "Floor load (kPa)" [:input {:id "structural-area-load" :type "number" :min 0 :value 3}]]
       [:label "Wind pressure (kPa)" [:input {:id "structural-wind-pressure" :type "number" :min 0 :value 1}]]
       [:label "Seismic coefficient" [:input {:id "structural-seismic-coefficient" :type "number" :min 0.001 :step 0.05 :value 0.2}]]
       [:button {:id "generate-structural-loads"} "Generate design loads"]
       [:label "Deformation scale" [:input {:id "structural-deformation-scale" :type "number" :min 0 :value 100}]]
       [:button {:id "run-structural-analysis"} "Run ULS + show results"]
       [:label "Structural span (m)" [:input {:id "structural-span" :type "number" :value 6}]]
       [:label "Axial load (kN)" [:input {:id "structural-load" :type "number" :value 100}]]
       [:button {:id "analyze-structure"} "Analyze member"]
       [:label "Pipe start" [:input {:id "pipe-start" :value "0,3,2.5"}]]
       [:label "Pipe end" [:input {:id "pipe-end" :value "8,3,2.5"}]]
       [:label "Pipe diameter (m)" [:input {:id "pipe-diameter" :type "number" :value 0.1}]]
       [:label "Design flow (L/s)" [:input {:id "pipe-flow" :type "number" :min 0 :value 5}]]
       [:label "Gravity slope (%)" [:input {:id "pipe-slope" :type "number" :min 0 :step 0.1 :value 0}]]
       [:button {:id "route-pipe"} "Route pipe"] [:div {:id "engineering-status"} "Ready"]
       [:h3 "Branched pipe network"]
       [:label "Source" [:input {:id "mep-network-source" :value "0,2,2.5"}]]
       [:label "Junction" [:input {:id "mep-network-junction" :value "4,2,2.5"}]]
       [:label "Terminal A" [:input {:id "mep-network-terminal-a" :value "8,1,2.5"}]]
       [:label "Terminal B" [:input {:id "mep-network-terminal-b" :value "8,4,2.5"}]]
       [:label "Terminal A demand (L/s)"
        [:input {:id "mep-network-demand-a" :type "number" :min 0.001 :value 3}]]
       [:label "Terminal B demand (L/s)"
        [:input {:id "mep-network-demand-b" :type "number" :min 0.001 :value 2}]]
       [:label "Maximum velocity (m/s)"
        [:input {:id "mep-network-max-velocity" :type "number" :min 0.1 :value 2}]]
       [:button {:id "design-mep-network"} "Design + route branched network"]
       [:h3 "Supply-air duct"]
       [:label "Duct start" [:input {:id "duct-start" :value "0,1,2.8"}]]
       [:label "Duct end" [:input {:id "duct-end" :value "8,5,2.8"}]]
       [:label "Design airflow (m³/s)"
        [:input {:id "duct-flow" :type "number" :min 0.001 :step 0.1 :value 1.2}]]
       [:label "Maximum air velocity (m/s)"
        [:input {:id "duct-max-velocity" :type "number" :min 0.1 :value 6}]]
       [:button {:id "route-duct"} "Size + route rectangular duct"]
       [:h3 "Electrical panel"]
       [:label "Panel location" [:input {:id "panel-point" :value "1,1,1.5"}]]
       [:label "Lighting load (VA)"
        [:input {:id "panel-load-a" :type "number" :min 1 :value 2300}]]
       [:label "Lighting run (m)"
        [:input {:id "panel-length-a" :type "number" :min 0.1 :value 30}]]
       [:label "Socket load (VA)"
        [:input {:id "panel-load-b" :type "number" :min 1 :value 1800}]]
       [:label "Socket run (m)"
        [:input {:id "panel-length-b" :type "number" :min 0.1 :value 20}]]
       [:label "Equipment load (VA)"
        [:input {:id "panel-load-c" :type "number" :min 1 :value 1500}]]
       [:label "Equipment run (m)"
        [:input {:id "panel-length-c" :type "number" :min 0.1 :value 15}]]
       [:label "Demand factor (%)"
        [:input {:id "panel-demand-factor" :type "number" :min 1 :max 100 :value 80}]]
       [:label "Main rating (A)"
        [:input {:id "panel-main-rating" :type "number" :min 1 :value 63}]]
       [:button {:id "design-electrical-panel"} "Design panel + circuits"]
       [:h3 "Radial electrical distribution"]
       [:label "Topology (EDN: :root-panel/:panels/:feeders/:protective-device-catalog)"
        [:textarea {:id "electrical-distribution-topology" :rows 10}
         "{:root-panel :main\n :panels [{:id :main :phases [:l1 :l2 :l3] :line-voltage-v 400.0 :main-rating-a 100.0 :circuits []}]\n :feeders []\n :protective-device-catalog [{:id :mccb-63 :rating-a 63.0 :breaking-capacity-a 10000.0 :instantaneous-trip-multiple 10.0}]}"]]
       [:button.primary {:id "analyze-electrical-distribution"} "Analyze radial distribution"]
       [:div {:id "electrical-distribution-status"} "No distribution analysis"]
       [:label "Equipment kind" [:select {:id "mep-equipment-kind"}
                                 [:option {:value "pump"} "Pump"]
                                 [:option {:value "air-terminal"} "Air terminal"]
                                 [:option {:value "fixture"} "Plumbing fixture"]]]
       [:label "Equipment point" [:input {:id "mep-equipment-point" :value "0,3,2.5"}]]
       [:label "Connector domain" [:select {:id "mep-connector-domain"}
                                  [:option {:value "piping"} "Piping"]
                                  [:option {:value "hvac"} "HVAC"]]]
       [:label "Connector size (m)" [:input {:id "mep-connector-size" :type "number" :min 0.001 :value 0.1}]]
       [:button {:id "add-mep-equipment"} "Add equipment / terminal"]
       [:label "Connector A ID" [:input {:id "mep-connector-a"}]]
       [:label "Connector B ID" [:input {:id "mep-connector-b"}]]
       [:button {:id "connect-mep-elements"} "Connect MEP elements"]
       [:div {:id "structural-model-status"} "No analytical model"]
       [:h2 "Rooms"] [:label "Width (m)" [:input {:id "room-width" :type "number" :value 4}]]
       [:label "Depth (m)" [:input {:id "room-depth" :type "number" :value 3}]]
       [:button {:id "add-room"} "＋ Room"] [:button {:id "auto-rooms"} "Generate enclosed rooms (RM)"]
       [:div {:id "rooms"}]
       [:label "Room name" [:input {:id "room-name" :value "Room"}]]
       [:label "Use" [:select {:id "room-category"}
                       (for [value ["residential" "office" "circulation" "service" "mechanical-room" "other"]]
                         [:option {:value value} value])]]
       [:button {:id "apply-room"} "Apply room properties"] [:button {:id "delete-room"} "Delete room"]
       [:h2 "Levels"] [:button {:id "add-level"} "＋ Add level"] [:div {:id "levels"}]
       [:h2 "Model tree"] [:div {:id "tree"}]
       [:h2 "Quantity schedule"] [:button {:id "export-schedule"} "Export CSV"] [:div {:id "quantity-schedule"}]
       [:h2 "Drawing annotations"]
       [:label "View top" [:input {:id "view-range-top" :type "number" :step 0.1 :value 3.2}]]
       [:label "Cut plane" [:input {:id "view-range-cut" :type "number" :step 0.1 :value 1.2}]]
       [:label "View bottom" [:input {:id "view-range-bottom" :type "number" :step 0.1 :value 0}]]
       [:label "View depth" [:input {:id "view-range-depth" :type "number" :step 0.1 :value -1}]]
       [:button {:id "apply-view-range"} "Apply view range"]
       [:label "Kind" [:select {:id "drawing-annotation-kind"}
                       [:option {:value "dimension"} "Dimension"]
                       [:option {:value "tag"} "Tag"]
                       [:option {:value "leader"} "Leader note"]
                       [:option {:value "revision-cloud"} "Revision cloud"]]]
       [:label "Points (x,y; …)" [:input {:id "drawing-annotation-points" :value "0,0;6,0"}]]
       [:label "Text" [:input {:id "drawing-annotation-text" :value "Note"}]]
       [:label "Revision" [:input {:id "drawing-annotation-revision" :value "P01"}]]
       [:label "Tag family" [:select {:id "annotation-family"}]]
       [:button {:id "auto-tag-elements"} "Auto-tag matching elements"]
       [:button.primary {:id "save-drawing-annotation"} "Add annotation"]
       [:button {:id "new-drawing-annotation"} "New annotation"]
       [:div {:id "drawing-annotations"}]
       [:div {:id "drawing-annotation-status"} "Annotations ready"]
       [:h2 "Print setup"]
       [:label "Paper" [:select {:id "print-paper"}
                        (for [value ["a0" "a1" "a2" "a3" "a4" "letter" "legal" "tabloid"]]
                          [:option {:value value :selected (= value "a1")} value])]]
       [:label "Orientation" [:select {:id "print-orientation"}
                              [:option {:value "landscape"} "Landscape"]
                              [:option {:value "portrait"} "Portrait"]]]
       [:label "Scale denominator" [:input {:id "print-scale" :type "number" :min 1 :value 100}]]
       [:label "Color" [:select {:id "print-color"}
                        [:option {:value "color"} "Color"]
                        [:option {:value "grayscale"} "Grayscale"]
                        [:option {:value "black-lines"} "Black lines"]]]
       [:button {:id "apply-print-setting"} "Apply print setup"]
       [:div {:id "print-status"} "Print ready"]
       [:h2 "Drawing sheets"]
       [:label "Organization" [:input {:id "title-block-organization" :value "Kotoba Architects"}]]
       [:label "Client" [:input {:id "title-block-client" :value "Client"}]]
       [:label "Drawn by" [:input {:id "title-block-drawn-by" :value "Designer"}]]
       [:label "Checked by" [:input {:id "title-block-checked-by" :value "Checker"}]]
       [:button.primary {:id "generate-drawing-set"} "Generate plans, sections + sheet"]
       [:div {:id "drawing-set-status"} "No drawing set"]
       [:h2 "Clash Detection"] [:button.primary {:id "run-clashes"} "Run Clash Check"]
       [:button {:id "export-clashes"} "Export Clash CSV"] [:div {:id "clash-results"} "No clashes"]]
      [:section.viewport [:canvas {:id "gpu-canvas" :aria-label "BIM WebGPU viewport"}]
       [:div {:id "gpu-status"} "Initializing WebGPU…"]
       [:div.viewport-help "Click: select · Orbit tool: drag view · Move tool: drag element · Esc: cancel"]
       [:div.drag-measure {:id "drag-measure" :style {:display "none"}}]
       [:div.snap-marker {:id "snap-marker" :style {:display "none"}}]
       [:div.selection-box {:id "selection-box" :style {:display "none"}}]
       [:div.stats {:id "stats"} "Loading model…"]]
      [:aside [:h2 {:id "inspector-title"} "Selected element"]
       [:label "Name" [:input {:id "name"}]] [:label "Length (m)" [:input {:id "length" :type "number" :step 0.1}]]
       [:label "Height (m)" [:input {:id "height" :type "number" :step 0.1}]]
       [:label "Thickness (m)" [:input {:id "thickness" :type "number" :step 0.05}]]
       [:label "Material" [:input {:id "material"}]] [:button.primary {:id "apply"} "Apply properties"]
       [:h2 "Transform"]
       [:label "Viewport tool" [:select {:id "viewport-tool"}
                                [:option {:value "orbit"} "Orbit"]
                                [:option {:value "move"} "Move selected"]
                                [:option {:value "box"} "Box select"]]]
       [:label "ΔX (m)" [:input {:id "move-x" :type "number" :step 0.1 :value 1}]]
       [:label "ΔY (m)" [:input {:id "move-y" :type "number" :step 0.1 :value 0}]]
       [:label "ΔZ (m)" [:input {:id "move-z" :type "number" :step 0.1 :value 0}]]
       [:button.primary {:id "move-element"} "Move (MV)"]
       [:button {:id "copy-element"} "Copy (CO)"]
       [:label "Snapping" [:input {:id "snap-enabled" :type "checkbox" :checked true}]]
       [:label "Grid (m)" [:input {:id "snap-grid" :type "number" :min 0.001 :step 0.1 :value 0.5}]]
       [:label "Tolerance (m)" [:input {:id "snap-tolerance" :type "number" :min 0.001
                                        :step 0.01 :value 0.15}]]
       [:div {:id "snap-status"} "Snap ready"]
       [:label "Angle (deg)" [:input {:id "transform-angle" :type "number" :step 1 :value 90}]]
       [:label "Pivot X" [:input {:id "pivot-x" :type "number" :step 0.1 :value 0}]]
       [:label "Pivot Y" [:input {:id "pivot-y" :type "number" :step 0.1 :value 0}]]
       [:label "Pivot Z" [:input {:id "pivot-z" :type "number" :step 0.1 :value 0}]]
       [:button {:id "rotate-element"} "Rotate (RO)"]
       [:label "Mirror normal X" [:input {:id "mirror-x" :type "number" :step 0.1 :value 1}]]
       [:label "Mirror normal Y" [:input {:id "mirror-y" :type "number" :step 0.1 :value 0}]]
       [:label "Mirror normal Z" [:input {:id "mirror-z" :type "number" :step 0.1 :value 0}]]
       [:button {:id "mirror-element"} "Mirror (MM)"]
       [:label "Array kind" [:select {:id "array-kind"}
                              [:option {:value "linear"} "Linear"]
                              [:option {:value "radial"} "Radial"]]]
       [:label "Copies" [:input {:id "array-count" :type "number" :min 1 :max 100 :step 1 :value 3}]]
       [:button {:id "array-element"} "Array (AR)"]
       [:h2 "Modify geometry"]
       [:label "Align axis" [:select {:id "align-axis"}
                              [:option {:value "x"} "X"] [:option {:value "y"} "Y"]
                              [:option {:value "z"} "Z"]]]
       [:label "Reference anchor" [:select {:id "align-reference-anchor"}
                                     [:option {:value "min"} "Minimum"]
                                     [:option {:value "center"} "Center"]
                                     [:option {:value "max"} "Maximum"]]]
       [:label "Moving anchor" [:select {:id "align-moving-anchor"}
                                  [:option {:value "min"} "Minimum"]
                                  [:option {:value "center"} "Center"]
                                  [:option {:value "max"} "Maximum"]]]
       [:button {:id "align-elements"} "Align (AL)"]
       [:label "Wall offset (m)" [:input {:id "wall-offset" :type "number" :step 0.1 :value 0.2}]]
       [:button {:id "offset-walls"} "Offset walls (OF)"]
       [:button {:id "trim-walls"} "Trim / Extend walls (TR)"]
       [:label "Join style" [:select {:id "wall-join-style"}
                              [:option {:value "butt"} "Butt / clean solids"]
                              [:option {:value "centerline"} "Centerline"]]]
       [:label "Join priority" [:select {:id "wall-join-priority"}
                                 [:option {:value "left"} "First selected"]
                                 [:option {:value "right"} "Second selected"]]]
       [:button {:id "join-walls"} "Join walls (WJ)"]
       [:label "Wall layers (material:thickness:category)"
        [:input {:id "wall-layers" :type "text"
                 :value "Gypsum:0.013:gypsum,Insulation:0.09:insulation,Concrete:0.20:concrete"}]]
       [:button {:id "apply-wall-layers"} "Apply wall layers (WL)"]
       [:label "Slab layers (material:thickness:category)"
        [:input {:id "slab-layers" :type "text"
                 :value "Finish:0.02:finish,Concrete:0.20:concrete"}]]
       [:button {:id "apply-slab-layers"} "Apply slab layers (SL)"]
       [:label "Slab vertex elevations (m)"
        [:input {:id "slab-elevations" :type "text" :value "0,0,0,0"}]]
       [:button {:id "apply-slab-shape"} "Apply slab shape (SE)"]
       [:h2 "Cloud collaboration"]
       [:label "cloud-itonami URL"
        [:input {:id "cloud-base-url" :type "url" :value "https://itonami.cloud"}]]
       [:label "Organization" [:input {:id "cloud-org" :value "gftdcojp"}]]
       [:label "Repository" [:input {:id "cloud-repo" :value "cloud-itonami"}]]
       [:label "CACAO capability token"
        [:input {:id "cloud-cacao" :type "password" :autocomplete "off"}]]
       [:label "Shaft X (m)" [:input {:id "shaft-x" :type "number" :step 0.1 :value 3}]]
       [:label "Shaft Y (m)" [:input {:id "shaft-y" :type "number" :step 0.1 :value 2}]]
       [:label "Shaft width (m)" [:input {:id "shaft-width" :type "number" :min 0.1 :step 0.1 :value 1}]]
       [:label "Shaft depth (m)" [:input {:id "shaft-depth" :type "number" :min 0.1 :step 0.1 :value 1}]]
       [:button {:id "add-shaft-opening"} "Add shaft opening (SO)"]
       [:label "Hosted offset (m)" [:input {:id "host-offset" :type "number" :min 0 :step 0.1 :value 1}]]
       [:label "Hosted sill (m)" [:input {:id "host-sill" :type "number" :min 0 :step 0.1 :value 0}]]
       [:button {:id "rehost-element"} "Rehost door/window (RH)"]
       [:div {:id "authoring-status"} "Modify ready"]
       [:button {:id "delete"} "Delete element"]]]
     [:span {:id "debug-state" :style {:display "none"}}] [:script {:src "./js/app.js"}]]]))
